### ISSUE TITLE
Cannot install on Linux

### ISSUE THREAD

**Issue by hyiso** [fvm-sh/fvm#7]
Currently using `unzip` to extract the downloaded archive, and failed on for Linux as the archive is *.tar.gz

**Comment by mkohlhaas** [comment]
OS is propertly recognized and FVM_OS is set to `linux` but still I cannot install any Flutter version. Maybe it has to do with the grep warnings but I couldn't find out.

```shell
$ fvm install 3.13.5
grep: warning: stray \ before "
grep: warning: stray \ before "
########################################################################################################################################################################################################################## 100.0%
fvm: unzip downloaded stable/linux/flutter_linux_3.13.5-stable.tar.xz failed, you can remove it by:
  rm /home/kohlhaas/.fvm/.cache/stable/linux/flutter_linux_3.13.5-stable.tar.xz
and install again:
  fvm install 3.13.5
bash: return: EXIT_CODE: numeric argument required
```

**Comment by qixiaoo** [comment]
This problem still exists after installing on Linux. It seems that the version installed is `v0.5.0`, which doesn't contain this fix. Would you mind releasing a new version and updating the `README.md`?

**Comment by hyiso** [comment]
Now fvm.sh  use `tar` instead of `unzip`, is your problem same with #10 ?

**Comment by qixiaoo** [comment]
Yes, same with #10 .

And running `git checkout main` in the `~/.fvm` directory can solve my problem.

**Comment by hyiso** [comment]
I'll release a new version for that
